### ISSUE TITLE
Consider using BER encoding for record count / field lengths

### ISSUE THREAD

**Issue by bradh** [sozip/keyvaluepairs-spec#2]
Instead of `kv_count` being a single `byte`, and `kv1_key_size` and `kv1_val_size` being little endian `uint16`, consider using BER encoding (so if its < 127, its a single byte, otherwise its extensible as needed). BER-OID encoding would also be an option.

**Comment by rouault** [comment]
Given the 64 KB limit of extra field content, you'll have trouble to encode subtantially more than 255 key/value pairs (and the use case with so many values is not clear to me), so byte is reaonable for kv_count.
For _key_size and _value_size, yes something more fancy could be done, but I'd like to keep things simple, and somewhat consisent with the "standard" third-party extra field content extensions that use fixed-size integers for similar purposes. That will make the life of implementors easier

**Comment by bradh** [comment]
I'm OK with this as a design decision.
